package pw.yumc.Residence.commandsub;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandException;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import com.bekvon.bukkit.residence.protection.ResidenceManager;

import cn.citycraft.PluginHelper.commands.BaseCommand;
import pw.yumc.Residence.ResidenceMain;
import pw.yumc.Residence.text.Language;

public class CommandListHidden extends BaseCommand {
    ResidenceMain plugin;

    public CommandListHidden(final ResidenceMain plugin) {
        super("lh");
        this.plugin = plugin;
        setOnlyPlayerExecutable();
    }

    @Override
    public void execute(final CommandSender sender, final Command command, final String label, final String[] args) throws CommandException {
        final Player player = (Player) sender;
        final boolean resadmin = (command != null);
        final ResidenceManager rmanager = plugin.getResidenceManager();
        final Language language = plugin.getLanguage();

        int page = 1;
        try {
            if (args.length > 0) {
                page = Integer.parseInt(args[args.length - 1]);
            }
        } catch (final Exception ex) {
        }

        if (!resadmin) {
            player.sendMessage(ChatColor.RED + language.getPhrase("NoPermission"));
            return;
        }

        switch (args.length) {
        case 0:
            rmanager.listResidences(player, 1, true);
            return;
        case 2:
            rmanager.listResidences(player, args[1], page, true);
            return;
        }
    }

}
